FROM elixir:1.18-alpine AS builder
WORKDIR /app
COPY erlang_sandbox/mix.exs erlang_sandbox/mix.lock ./
COPY erlang_sandbox/config ./config
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get --only prod
COPY erlang_sandbox/lib ./lib
RUN MIX_ENV=prod mix release

FROM elixir:1.18-alpine AS prod
WORKDIR /app
COPY --from=builder /app/_build/prod/rel/erlang_sandbox ./
EXPOSE 4000
CMD ["bin/erlang_sandbox", "start"]
