FROM elixir:latest

RUN apt-get update && apt install -y make sudo &&\
    apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /erlang_sandbox

COPY /erlang_sandbox .

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get

RUN mix deps.compile && mix compile

EXPOSE 4000

CMD ["mix", "run", "--no-halt"]